-d D:\BaiduNetdiskDownload\Runber_Gowin_Board_sourse\course_prj\course13_Lock\lock\impl\gwsynthesis\lock.vg
-p GW1N-4-LQFP144-6
-pn GW1N-UV4LQ144C6/I5
-cst D:\BaiduNetdiskDownload\Runber_Gowin_Board_sourse\course_prj\course13_Lock\lock\src\lock.cst
-cfg D:\BaiduNetdiskDownload\Runber_Gowin_Board_sourse\course_prj\course13_Lock\lock\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
